/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/activityDetail`; params?: Router.UnknownInputParams; } | { pathname: `/addActivity`; params?: Router.UnknownInputParams; } | { pathname: `/editProfile`; params?: Router.UnknownInputParams; } | { pathname: `/home`; params?: Router.UnknownInputParams; } | { pathname: `/home2`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/leaderboard`; params?: Router.UnknownInputParams; } | { pathname: `/login`; params?: Router.UnknownInputParams; } | { pathname: `/organizationProfile`; params?: Router.UnknownInputParams; } | { pathname: `/profile`; params?: Router.UnknownInputParams; } | { pathname: `/signup`; params?: Router.UnknownInputParams; } | { pathname: `/welcome`; params?: Router.UnknownInputParams; } | { pathname: `/../context/AuthContext`; params?: Router.UnknownInputParams; } | { pathname: `/../helper/api`; params?: Router.UnknownInputParams; } | { pathname: `/testapi`; params?: Router.UnknownInputParams; } | { pathname: `/../helper/styles`; params?: Router.UnknownInputParams; } | { pathname: `/userEvents`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/activityDetail`; params?: Router.UnknownOutputParams; } | { pathname: `/addActivity`; params?: Router.UnknownOutputParams; } | { pathname: `/editProfile`; params?: Router.UnknownOutputParams; } | { pathname: `/home`; params?: Router.UnknownOutputParams; } | { pathname: `/home2`; params?: Router.UnknownOutputParams; } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/leaderboard`; params?: Router.UnknownOutputParams; } | { pathname: `/login`; params?: Router.UnknownOutputParams; } | { pathname: `/organizationProfile`; params?: Router.UnknownOutputParams; } | { pathname: `/profile`; params?: Router.UnknownOutputParams; } | { pathname: `/signup`; params?: Router.UnknownOutputParams; } | { pathname: `/welcome`; params?: Router.UnknownOutputParams; } | { pathname: `/../context/AuthContext`; params?: Router.UnknownOutputParams; } | { pathname: `/../helper/api`; params?: Router.UnknownOutputParams; } | { pathname: `/testapi`; params?: Router.UnknownOutputParams; } | { pathname: `/../helper/styles`; params?: Router.UnknownOutputParams; } | { pathname: `/userEvents`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/activityDetail${`?${string}` | `#${string}` | ''}` | `/addActivity${`?${string}` | `#${string}` | ''}` | `/editProfile${`?${string}` | `#${string}` | ''}` | `/home${`?${string}` | `#${string}` | ''}` | `/home2${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `/leaderboard${`?${string}` | `#${string}` | ''}` | `/login${`?${string}` | `#${string}` | ''}` | `/organizationProfile${`?${string}` | `#${string}` | ''}` | `/profile${`?${string}` | `#${string}` | ''}` | `/signup${`?${string}` | `#${string}` | ''}` | `/welcome${`?${string}` | `#${string}` | ''}` | `/../context/AuthContext${`?${string}` | `#${string}` | ''}` | `/../helper/api${`?${string}` | `#${string}` | ''}` | `/testapi${`?${string}` | `#${string}` | ''}` | `/../helper/styles${`?${string}` | `#${string}` | ''}` | `/userEvents${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/activityDetail`; params?: Router.UnknownInputParams; } | { pathname: `/addActivity`; params?: Router.UnknownInputParams; } | { pathname: `/editProfile`; params?: Router.UnknownInputParams; } | { pathname: `/home`; params?: Router.UnknownInputParams; } | { pathname: `/home2`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/leaderboard`; params?: Router.UnknownInputParams; } | { pathname: `/login`; params?: Router.UnknownInputParams; } | { pathname: `/organizationProfile`; params?: Router.UnknownInputParams; } | { pathname: `/profile`; params?: Router.UnknownInputParams; } | { pathname: `/signup`; params?: Router.UnknownInputParams; } | { pathname: `/welcome`; params?: Router.UnknownInputParams; } | { pathname: `/../context/AuthContext`; params?: Router.UnknownInputParams; } | { pathname: `/../helper/api`; params?: Router.UnknownInputParams; } | { pathname: `/testapi`; params?: Router.UnknownInputParams; } | { pathname: `/../helper/styles`; params?: Router.UnknownInputParams; } | { pathname: `/userEvents`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; };
    }
  }
}
